const educationMotivationalQuotes = [
  "Education is the passport to the future, for tomorrow belongs to those who prepare for it today. - Malcolm X",
  "Education is the most powerful weapon which you can use to change the world. - Nelson Mandela",
  "The beautiful thing about learning is that nobody can take it away from you. - B.B. King",
  "Education is not preparation for life; education is life itself. - John Dewey",
  "An investment in knowledge pays the best interest. - Benjamin Franklin",
  "Education is the key to unlock the golden door of freedom. - George Washington Carver",
  "The more that you read, the more things you will know. The more that you learn, the more places you'll go. - Dr. Seuss",
  "The only person who is educated is the one who has learned how to learn and change. - Carl Rogers",
  "The roots of education are bitter, but the fruit is sweet. - Aristotle",
  "Education is not just about going to school and getting a degree. It's about widening your knowledge and absorbing the truth about life. - Shakuntala Devi",
  "Education is the best provision for old age. - Aristotle",
  "Learning is not attained by chance; it must be sought for with ardor and diligence. - Abigail Adams",
  "The mind once enlightened cannot again become dark. - Thomas Paine",
  "Education is not preparation for life; education is life itself. - John Dewey",
  "Learning is not attained by chance; it must be sought for with ardor and diligence. - Abigail Adams",
  "The roots of education are bitter, but the fruit is sweet. - Aristotle",
  "Intelligence plus character—that is the goal of true education. - Martin Luther King Jr.",
  "The more that you read, the more things you will know. The more that you learn, the more places you'll go. - Dr. Seuss",
  "Education is not the filling of a pail, but the lighting of a fire. - William Butler Yeats",
  "Education is the ability to listen to almost anything without losing your temper or your self-confidence. - Robert Frost",
  "Education is not the learning of facts, but the training of the mind to think. - Albert Einstein",
  "Education is the best provision for old age. - Aristotle",
  "Education is what remains after one has forgotten what one has learned in school. - Albert Einstein",
  "The expert in anything was once a beginner. - Helen Hayes",
  "Education is not the filling of a pail, but the lighting of a fire. - William Butler Yeats",
  "The best way to predict the future is to create it. - Abraham Lincoln",
  "Education is not preparation for life; education is life itself. - John Dewey",
  "Education is not the learning of facts, but the training of the mind to think. - Albert Einstein",
  "The beautiful thing about learning is that no one can take it away from you. - B.B. King",
  "Learning is a treasure that will follow its owner everywhere. - Chinese Proverb",
  "Education is the key to unlock the golden door of freedom. - George Washington Carver",
  "Education is the movement from darkness to light. - Allan Bloom",
  "You are always a student, never a master. You have to keep moving forward. - Conrad Hall",
  "Education is the foundation upon which we build our future. - Christine Gregoire",
  "An investment in knowledge pays the best interest. - Benjamin Franklin",
  "Education is the most powerful weapon which you can use to change the world. - Nelson Mandela",
  "Education is the passport to the future, for tomorrow belongs to those who prepare for it today. - Malcolm X",
  "Education is not just about going to school and getting a degree. It's about widening your knowledge and absorbing the truth about life. - Shakuntala Devi",
  "Education is not preparation for life; education is life itself. - John Dewey",
  "Learning is not attained by chance; it must be sought for with ardor and diligence. - Abigail Adams",
  "The roots of education are bitter, but the fruit is sweet. - Aristotle",
  "Intelligence plus character—that is the goal of true education. - Martin Luther King Jr.",
  "The more that you read, the more things you will know. The more that you learn, the more places you'll go. - Dr. Seuss",
  "Education is not the filling of a pail, but the lighting of a fire. - William Butler Yeats",
  "Education is the ability to listen to almost anything without losing your temper or your self-confidence. - Robert Frost",
  "Education is not the learning of facts, but the training of the mind to think. - Albert Einstein",
  "Education is the best provision for old age. - Aristotle",
  "Education is what remains after one has forgotten what one has learned in school. - Albert Einstein",
  "The expert in anything was once a beginner. - Helen Hayes",
  "Education is not the filling of a pail, but the lighting of a fire. - William Butler Yeats",
  "The best way to predict the future is to create it. - Abraham Lincoln",
  "Education is not preparation for life; education is life itself. - John Dewey",
  "Education is not the learning of facts, but the training of the mind to think. - Albert Einstein",
  "The beautiful thing about learning is that no one can take it away from you. - B.B. King",
  "Learning is a treasure that will follow its owner everywhere. - Chinese Proverb",
  "Education is the key to unlock the golden door of freedom. - George Washington Carver",
  "Education is the movement from darkness to light. - Allan Bloom",
  "You are always a student, never a master. You have to keep moving forward. - Conrad Hall",
  "Education is the foundation upon which we build our future. - Christine Gregoire",
  "An investment in knowledge pays the best interest. - Benjamin Franklin",
  "Education is the most powerful weapon which you can use to change the world. - Nelson Mandela",
  "Education is the passport to the future, for tomorrow belongs to those who prepare for it today. - Malcolm X",
  "Education is not just about going to school and getting a degree. It's about widening your knowledge and absorbing the truth about life. - Shakuntala Devi",
  "Education is not preparation for life; education is life itself. - John Dewey",
  "Learning is not attained by chance; it must be sought for with ardor and diligence. - Abigail Adams",
  "The roots of education are bitter, but the fruit is sweet. - Aristotle",
  "Intelligence plus character—that is the goal of true education. - Martin Luther King Jr.",
  "The more that you read, the more things you will know. The more that you learn, the more places you'll go. - Dr. Seuss",
  "Education is not the filling of a pail, but the",
  "Coding is like magic; you turn imagination into reality.",
  "Debugging is like being the detective in a crime movie where you are also the murderer.",
  "Embrace the bugs, for they are the stepping stones to improvement.",
  "In the world of software, there are no limits to what you can create.",
  "Code is poetry; let your creativity flow through every line.",
  "A programmer's mind is a canvas of endless possibilities.",
  "Failure is just a compile error; keep iterating until you get it right.",
  "The best code is not just functional but elegant and maintainable.",
  "Don't fear challenges; they are opportunities to learn and grow.",
  "Continuous improvement is the key to becoming a master coder.",
  "Software is a manifestation of your ideas brought to life.",
  "A well-designed program is like a symphony that harmonizes perfectly.",
  "As a coder, you have the power to change the world one line of code at a time.",
  "The software you create can impact millions; aim for greatness.",
  "Every line of code written with passion has the potential to create a masterpiece.",
  "Being a software engineer means being a lifelong learner in the ever-evolving world of tech.",
  "In software development, perseverance and patience are the keys to success.",
  "The beauty of coding is the ability to create something out of nothing.",
  "Complex problems in coding lead to ingenious solutions.",
  "Coding is not just a skill; it's an art form that requires dedication and creativity.",
  "A successful coder is a master at balancing efficiency and readability.",
  "The thrill of coding lies in the moment your creation comes to life.",
  "In the world of software, innovation is the driving force of progress.",
  "A software engineer's journey is a continuous quest for excellence.",
  "Solving coding challenges is like solving puzzles that expand your mind.",
  "The possibilities in software development are limited only by your imagination.",
  "Code is the language of the future, and you are its storyteller.",
  "Bugs are opportunities in disguise; they lead you to a better solution.",
  "Software engineering is a journey of discovery, curiosity, and innovation.",
  "The world of coding is a playground for your wildest ideas.",
  "The art of coding lies in turning complexity into simplicity.",
  "Coding is not just about writing code; it's about solving problems elegantly.",
  "Your code is a reflection of who you are as a developer; make it a masterpiece.",
  "Embrace the challenges, for they sharpen your coding skills and expand your horizons.",
  "In the vast ocean of code, you are the captain of your ship.",
  "Every bug fixed is a victory in the journey of software development.",
  "Coding is a never-ending adventure, where every line of code is a new frontier.",
  "As a software engineer, you are not bound by limitations; you create possibilities.",
  "Behind every great software is a dedicated coder who made it possible.",
  "A software engineer is a dreamer, an architect, and a problem solver all in one.",
  "Coding is not just a profession; it's a passion that fuels innovation.",
  "The joy of coding lies in the thrill of conquering new challenges.",
  "Every line of code you write is a brushstroke on the canvas of technology.",
  "As a coder, you wield the power to shape the digital world we live in.",
  "Coding is an art, and every masterpiece begins with a blank canvas.",
  "A true coder never stops learning and exploring the vast realm of possibilities.",
  "Coding is like composing a symphony; every element must harmonize flawlessly.",
  "In coding, there is always a solution waiting to be discovered.",
  "Success in coding comes from the journey of continuous improvement.",
  "As a software engineer, you are not just a builder; you are an innovator.",
  "Coding is an ever-evolving dance between logic and creativity.",
  "The thrill of coding is the pursuit of perfection in an imperfect world.",
  "In software development, every challenge is an invitation to create something extraordinary.",
  "A software engineer's mind is a playground of curiosity and imagination.",
  "Every bug is a puzzle; solving it is an adventure of its own.",
  "Coding is the language through which dreams become reality in the digital world.",
  "In coding, you are not limited by resources; you are empowered by ideas.",
  "As a coder, you breathe life into machines and make the impossible possible.",
  "The art of coding lies in the finesse of turning complexity into simplicity.",
  "In coding, the smallest details can make the biggest difference.",
  "Your code is an extension of your thoughts; let it speak your brilliance.",
  "Coding is not just a profession; it's a journey of self-discovery and growth.",
];

const emailSubjects = [
  "Your Daily Dose of Motivation 🚀",
  "Start Your Day Inspired: Daily Motivation Inside 🌟",
  "Uplifting Thoughts for You Today 🌞",
  "Empowering Quotes to Kickstart Your Day 💪",
  "Fuel Your Day with Motivation 🌈",
  "Motivational Quote of the Day 📅",
  "Boost Your Spirits with Today's Motivation 🚀",
  "Your Daily Inspiration Awaits 🌟",
  "Get Inspired: Daily Motivation Just for You 🌞",
  "Brighten Your Day with Daily Motivational Quotes 🌈",
  "Start Your Day on a Positive Note 💪",
  "Motivation in Your Inbox 📧",
  "Daily Motivation for a Productive Day 🚀",
  "Awaken Your Potential with Daily Inspiration 🌟",
  "Stay Inspired: Daily Quotes for You 🌞",
  "Empower Yourself Today with Motivation 🌈",
  "Daily Motivation to Reach Your Goals 💪",
  "Motivational Boost: Your Daily Quote 🚀",
  "Your Daily Dose of Positivity 🌟",
  "Fuel Your Day with Inspiration 🌞",
  "Unleash Your Inner Greatness 🌟",
  "Rise and Shine with Motivation 🌞",
  "Be Inspired, Be Unstoppable 💪",
  "Your Path to Success Starts Here 🚀",
  "Embrace the Power of Motivation 🌈",
  "Motivation for a Brighter Tomorrow 🌟",
  "Ignite Your Passion with Daily Quotes 🚀",
  "Seize the Day with Inspirational Quotes 🌞",
  "Find Your Daily Spark of Motivation 🔥",
  "Stay Focused, Stay Motivated 💪",
  "Inspiration for a Purposeful Life 🌟",
  "Daily Motivation for Success 🚀",
  "Unlock Your Potential with Daily Inspiration 🌈",
  "Let Motivation Guide Your Journey 🌞",
  "Conquer Your Day with Motivated Energy 💪",
  "Amp Up Your Positivity with Daily Quotes 🌟",
  "Fuel Your Dreams with Motivation 🚀",
  "Positive Vibes Only: Your Daily Motivation 🌞",
  "Rise Above Challenges with Daily Inspiration 🌈",
  "Dare to Dream, Stay Inspired 🌟",
  "Your Motivational Oasis Awaits 🚀",
  "Today's Motivation for Tomorrow's Success 🌞",
  "Believe in Yourself: Daily Motivation 💪",
  "Daily Quotes to Brighten Your Spirit 🌟",
  "Find Strength in Daily Motivation 🌈",
  "Fuel Your Ambition with Daily Inspiration 🚀",
  "Your Daily Pep Talk for Greatness 🌞",
  "Inspiration to Elevate Your Life 🌟",
  "Daily Motivation to Empower You 💪",
  "Awe-Inspiring Quotes for Your Day 🚀",
  "Fuel Your Passion with Daily Inspiration 🌈",
  "Start Your Day with a Positive Mindset 🌞",
  "Motivation: Your Secret to Success 🌟",
  "Daily Quotes to Ignite Your Fire 🔥",
  "Embrace Daily Inspiration for Growth 🚀",
  "Your Path to Greatness Begins Today 🌞",
  "Stay Inspired, Stay Motivated 💪",
  "Daily Motivation for a Life of Purpose 🌟",
  "Elevate Your Potential with Daily Quotes 🌈",
  "Empower Yourself with Daily Inspiration 🚀",
  "Your Daily Dose of Positivity 🌞",
  "Fuel Your Dreams with Motivation 🌟",
  "Inspiration to Overcome and Succeed 💪",
  "Daily Quotes for a Brilliant Mindset 🚀",
  "Find Your Inner Drive with Daily Inspiration 🌈",
  "Aim High with Daily Motivation 🌞",
  "Inspire Greatness within Yourself 🌟",
  "Your Daily Reminder: You've Got This! 💪",
  "Daily Motivation to Conquer Challenges 🚀",
  "Fuel Your Soul with Inspirational Quotes 🌞",
  "Achieve Your Best Self with Motivation 🌈",
  "Your Journey, Your Motivation 🌟",
  "Unleash Your Potential with Daily Inspiration 🔥",
  "Believe in the Power of Daily Quotes 🚀",
  "Motivation to Soar to New Heights 🌞",
  "Embrace Change with Daily Inspiration 🌈",
  "Seize Opportunities with Daily Motivation 🌟",
  "Stay Positive, Stay Motivated 💪",
  "Daily Motivation to Chase Your Dreams 🚀",
  "Ignite Your Passion with Inspirational Quotes 🌞",
  "Empower Yourself with Daily Motivation 🌈",
  "Your Daily Source of Positivity 🌟",
  "Fuel Your Ambition with Motivation 💪",
  "Rise Above Challenges with Daily Inspiration 🚀",
  "Daily Quotes to Elevate Your Mindset 🌞",
  "Motivation for Success and Happiness 🌈",
  "Unlock Your Potential with Daily Inspiration 🌟",
  "Stay Inspired, Stay Motivated 💪",
  "Your Daily Pep Talk for Greatness 🚀",
  "Inspiration to Elevate Your Life 🌞",
  "Daily Motivation to Empower You 🔥",
  "Awe-Inspiring Quotes for Your Day 🌈",
  "Fuel Your Passion with Daily Inspiration 🌟",
  "Start Your Day with a Positive Mindset 🚀",
  "Motivation: Your Secret to Success 🌞",
  "Daily Quotes to Ignite Your Fire 🔥",
  "Embrace Daily Inspiration for Growth 🌈",
];

module.exports = { educationMotivationalQuotes, emailSubjects };
